version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/tmp

    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Configure ENV files based on environment
          command: |
            echo "Setting AWS environment"
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region us-east-1
      - run:
          name: Zip and deploy Lambda Functions
          command: |
            ROOT=$PWD
            # iterate through lambdas
            for LAMBDA_PATH in services/*/
            do
                FUNCTION_NAME=$(basename $LAMBDA_PATH)
                if [[ -f services/$FUNCTION_NAME/requirements.txt ]]; then
                  echo "Installing packages..."
                  pip install -r services/$FUNCTION_NAME/requirements.txt --target services/$FUNCTION_NAME/packages/ --find-links ./packages
                fi
                cd services/$FUNCTION_NAME
                echo "Building $FUNCTION_NAME..."
                zip main.zip *.py */ -r
                echo "Deploying $FUNCTION_NAME..."
                aws lambda update-function-code --function-name $FUNCTION_NAME --region us-east-1 --zip-file fileb://main.zip
                cd $ROOT
            done
workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only:
              - main
